include("${CMAKE_CURRENT_LIST_DIR}/project_helpers.cmake")
file(WRITE "${project_root}/host/default.txt" "// Empty host API\n")
file(WRITE "${project_root}/src/main.vas" "void main() {}\n")
file(MAKE_DIRECTORY "${project_root}/existing")
file(WRITE "${project_root}/existing/keep.vasbc" "previous successful artifact")

# No output writes or mkdir happen before successful input setup + compilation.
write_project("${project_file}" src/main.vas host/default.txt existing/keep.vasbc)
run_report(OFF arguments OFF --project "${project_file}" --unit unknown)
expect_file_text("${project_root}/existing/keep.vasbc" "previous successful artifact")
file(WRITE "${project_root}/host/invalid.txt" "func \"not a declaration\"\n")
write_project("${project_file}" src/main.vas host/invalid.txt existing/keep.vasbc)
run_report(OFF config OFF --project "${project_file}" --unit main)
expect_file_text("${project_root}/existing/keep.vasbc" "previous successful artifact")
write_project("${project_file}" src/main.vas host/invalid.txt new/config/out.vasbc)
run_report(OFF config OFF --project "${project_file}" --unit main)
expect_no_path("${project_root}/new")
file(WRITE "${project_root}/src/main.vas" "void main() { unknown(); }\n")
write_project("${project_file}" src/main.vas host/default.txt existing/keep.vasbc)
run_report(OFF compile ON --project "${project_file}" --unit main)
expect_file_text("${project_root}/existing/keep.vasbc" "previous successful artifact")
write_project("${project_file}" src/main.vas host/default.txt new/compile/out.vasbc)
run_report(OFF compile ON --project "${project_file}" --unit main)
expect_no_path("${project_root}/new")
file(WRITE "${project_root}/src/main.vas" "void main() {}\n")

# Existing directories are not acceptable selected input files.
file(MAKE_DIRECTORY "${project_root}/entry-directory.vas" "${project_root}/config-directory.txt")
write_project("${project_file}" entry-directory.vas host/default.txt new/directory/out.vasbc)
run_report(OFF load OFF --project "${project_file}" --unit main)
expect_no_path("${project_root}/new")
write_project("${project_file}" src/main.vas config-directory.txt new/directory/out.vasbc)
run_report(OFF config OFF --project "${project_file}" --unit main)
expect_no_path("${project_root}/new")

# Entry, host config, manifest, and every actually loaded include are protected
# even though bytecode output has no filename-extension restriction.
foreach(destination IN ITEMS src/main.vas host/default.txt vas-project.json)
	write_project("${project_file}" src/main.vas host/default.txt "${destination}")
	file(SHA256 "${project_root}/${destination}" before)
	run_report(OFF output ON --project "${project_file}" --unit main)
	file(SHA256 "${project_root}/${destination}" after)
	expect_equal("${after}" "${before}" "protected input ${destination}")
endforeach()
file(WRITE "${project_root}/src/included.vas" "void included() {}\n")
file(WRITE "${project_root}/src/main.vas" "#include \"included.vas\"\nvoid main() { included(); }\n")
write_project("${project_file}" src/main.vas host/default.txt src/included.vas)
file(SHA256 "${project_root}/src/included.vas" before)
run_report(OFF output ON --project "${project_file}" --unit main)
expect_count(section_loaded 2)
file(SHA256 "${project_root}/src/included.vas" after)
expect_equal("${after}" "${before}" "protected loaded include")

# Inputs declared by unselected units are protected too. Dormant availability
# is optional, but a selected build cannot corrupt a present dormant input.
file(WRITE "${project_root}/src/dormant.vas" "void dormant() {}\n")
file(WRITE "${project_root}/host/dormant.txt" "// dormant host declarations\n")
project_unit(dormant dormant src/dormant.vas host/dormant.txt build/dormant.vasbc)
foreach(destination IN ITEMS src/dormant.vas host/dormant.txt)
	project_unit(selected main src/main.vas host/default.txt "${destination}")
	file(WRITE "${project_file}" "{\"schemaVersion\":1,\"compilationUnits\":[${selected},${dormant}]}")
	file(SHA256 "${project_root}/${destination}" before)
	run_report(OFF output ON --project "${project_file}" --unit main)
	file(SHA256 "${project_root}/${destination}" after)
	expect_equal("${after}" "${before}" "protected unselected input ${destination}")
endforeach()
project_unit(dormant dormant absent/dormant.vas absent/dormant.txt absent/dormant.vasbc)
project_unit(selected main src/main.vas host/default.txt existing/selected.vasbc)
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"compilationUnits\":[${selected},${dormant}]}")
run_report(ON output ON --project "${project_file}" --unit main)
expect_no_path("${project_root}/absent")

file(MAKE_DIRECTORY "${project_root}/directory-output")
write_project("${project_file}" src/main.vas host/default.txt directory-output)
run_report(OFF output ON --project "${project_file}" --unit main)
file(WRITE "${project_root}/blocked-parent" "not a directory")
write_project("${project_file}" src/main.vas host/default.txt blocked-parent/deep/out.vasbc)
run_report(OFF output ON --project "${project_file}" --unit main)
expect_file_text("${project_root}/blocked-parent" "not a directory")

# Distinct regular-file names can identify one inode. Reject multiply-linked
# destinations even when none of the other names is a known compiler input.
file(WRITE "${project_root}/existing/hard-source" "unrelated multiply-linked bytes")
file(CREATE_LINK "${project_root}/existing/hard-source" "${project_root}/existing/hard-output" RESULT hardlink_error)
if(hardlink_error STREQUAL "0")
	write_project("${project_file}" src/main.vas host/default.txt existing/hard-output)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_file_text("${project_root}/existing/hard-source" "unrelated multiply-linked bytes")
	expect_file_text("${project_root}/existing/hard-output" "unrelated multiply-linked bytes")
	project_unit(selected main src/main.vas host/default.txt existing/hard-output)
	project_unit(other other src/main.vas host/default.txt existing/hard-source)
	file(WRITE "${project_file}" "{\"schemaVersion\":1,\"compilationUnits\":[${selected},${other}]}")
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_file_text("${project_root}/existing/hard-source" "unrelated multiply-linked bytes")
else()
	message(STATUS "Hard-link conformance unavailable on this filesystem: ${hardlink_error}")
endif()

# Symlink/reparse behavior is exercised where creating links is permitted.
# Windows CI without Developer Mode may legitimately skip these cases.
file(MAKE_DIRECTORY "${workspace}/outside")
file(WRITE "${workspace}/outside/host.txt" "// external host\n")
file(WRITE "${workspace}/outside/main.vas" "void main() {}\n")
file(WRITE "${workspace}/outside/keep.vasbc" "outside bytes")
file(CREATE_LINK "${workspace}/outside" "${project_root}/escape" SYMBOLIC RESULT symlink_error)
if(symlink_error STREQUAL "0")
	write_project("${project_file}" src/main.vas escape/host.txt absent/config/out.vasbc)
	run_descriptor(ON "${project_file}")
	run_report(OFF config OFF --project "${project_file}" --unit main)
	expect_count(section_loaded 0)
	expect_no_path("${project_root}/absent")
	write_project("${project_file}" escape/main.vas host/default.txt absent/entry/out.vasbc)
	run_report(OFF load OFF --project "${project_file}" --unit main)
	expect_count(section_loaded 0)
	expect_no_path("${project_root}/absent")
	write_project("${project_file}" src/main.vas host/default.txt escape/keep.vasbc)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_file_text("${workspace}/outside/keep.vasbc" "outside bytes")
	write_project("${project_file}" src/main.vas host/default.txt escape/new/deep/out.vasbc)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_no_path("${workspace}/outside/new")

	# Final symlinks are rejected even when they resolve back inside the root.
	file(CREATE_LINK "${project_root}/existing/keep.vasbc" "${project_root}/linked-output" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "in-root output symlink fixture")
	write_project("${project_file}" src/main.vas host/default.txt linked-output)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_file_text("${project_root}/existing/keep.vasbc" "previous successful artifact")
	file(CREATE_LINK "${workspace}/outside/missing.vasbc" "${project_root}/dangling-output" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "dangling output symlink fixture")
	write_project("${project_file}" src/main.vas host/default.txt dangling-output)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_no_path("${workspace}/outside/missing.vasbc")

	# In-root symlinked inputs are allowed, but the real include they identify
	# remains protected if output names that target through a different path.
	file(CREATE_LINK "${project_root}/src/included.vas" "${project_root}/src/alias.vas" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "include symlink fixture")
	file(WRITE "${project_root}/src/main.vas" "#include \"alias.vas\"\nvoid main() { included(); }\n")
	write_project("${project_file}" src/main.vas host/default.txt src/included.vas)
	file(SHA256 "${project_root}/src/included.vas" before)
	run_report(OFF output ON --project "${project_file}" --unit main)
	file(SHA256 "${project_root}/src/included.vas" after)
	expect_equal("${after}" "${before}" "protected real include target")
	file(CREATE_LINK "${project_root}/src/main.vas" "${project_root}/entry-link.vas" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "entry symlink fixture")
	file(CREATE_LINK "${project_root}/host/default.txt" "${project_root}/config-link.txt" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "config symlink fixture")
	# Use a standalone source so its lexical include base does not move.
	file(WRITE "${project_root}/src/main.vas" "void main() {}\n")
	write_project("${project_file}" entry-link.vas config-link.txt new/allowed/out.vasbc)
	run_report(ON output ON --project "${project_file}" --unit main)
	file(MAKE_DIRECTORY "${project_root}/inside-parent")
	file(CREATE_LINK "${project_root}/inside-parent" "${project_root}/parent-link" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "contained output parent symlink fixture")
	write_project("${project_file}" src/main.vas host/default.txt parent-link/deep/out.vasbc)
	run_report(ON output ON --project "${project_file}" --unit main)
	if(NOT EXISTS "${project_root}/inside-parent/deep/out.vasbc")
		message(FATAL_ERROR "Allowed in-root real output parent was not used")
	endif()

	# Merely sharing the root name's prefix does not establish containment.
	file(MAKE_DIRECTORY "${project_root}-sibling")
	file(CREATE_LINK "${project_root}-sibling" "${project_root}/prefix-escape" SYMBOLIC RESULT link_error)
	expect_equal("${link_error}" 0 "prefix-sibling symlink fixture")
	write_project("${project_file}" src/main.vas host/default.txt prefix-escape/new/out.vasbc)
	run_report(OFF output ON --project "${project_file}" --unit main)
	expect_no_path("${project_root}-sibling/new")
else()
	message(STATUS "Symlink conformance unavailable on this platform: ${symlink_error}")
endif()

# A nonregular final destination must be rejected without opening a FIFO, which
# otherwise blocks indefinitely. UNIX-only creation uses the native mkfifo tool.
if(UNIX)
	find_program(MKFIFO mkfifo)
	if(MKFIFO)
		execute_process(COMMAND "${MKFIFO}" "${project_root}/fifo-output" RESULT_VARIABLE result)
		expect_equal("${result}" 0 "FIFO fixture creation")
		write_project("${project_file}" src/main.vas host/default.txt fifo-output)
		run_report(OFF output ON --project "${project_file}" --unit main)
	endif()
endif()

# Same-file stdout aliases are identified even though report capture creates the
# regular file before process launch; only JSONL, never bytecode, may appear.
set(capture "${project_root}/same-output.jsonl")
write_project("${project_file}" src/main.vas host/default.txt same-output.jsonl)
execute_process(COMMAND "${VASBUILD}" --report=jsonl --project "${project_file}" --unit main
	WORKING_DIRECTORY "${workspace}" RESULT_VARIABLE result OUTPUT_FILE "${capture}"
	ERROR_VARIABLE err ENCODING NONE TIMEOUT 20)
if("${result}" STREQUAL "0")
	message(FATAL_ERROR "Project output aliasing stdout unexpectedly succeeded")
endif()
expect_equal("${err}" "" "stdout-alias stderr")
file(READ "${capture}" text)
parse_report("${text}")
expect_json("${record_${report_count}}" OFF success)
expect_json("${record_${report_count}}" output phase)
expect_json("${record_${report_count}}" ON dependenciesComplete)
