include("${CMAKE_CURRENT_LIST_DIR}/project_helpers.cmake")

file(SHA256 "${project_file}" before)
run_descriptor(ON "${project_file}")
expect_json("${descriptor}" "${project_file}" project)
expect_json("${descriptor}" "${project_root}" projectRoot)
expect_json("${descriptor}" OFF legacyProject)
expect_json("${descriptor}" "Native contract 文😀" name)
string(JSON count LENGTH "${descriptor}" compilationUnits)
expect_equal("${count}" 2 "compilation unit count")
string(JSON count LENGTH "${descriptor}" warnings)
expect_equal("${count}" 0 "v1 warnings")
expect_json("${descriptor}" main compilationUnits 0 id)
expect_json("${descriptor}" "${project_root}/src/main.vas" compilationUnits 0 entry)
expect_json("${descriptor}" "${project_root}/host/default.txt" compilationUnits 0 hostApi config)
expect_json("${descriptor}" "${project_root}/build/main.vasbc" compilationUnits 0 output)
expect_json("${descriptor}" other-host compilationUnits 1 id)
expect_json("${descriptor}" "${project_root}/src/main.vas" compilationUnits 1 entry)
expect_json("${descriptor}" "${project_root}/host/alternate.txt" compilationUnits 1 hostApi config)
file(SHA256 "${project_file}" after)
expect_equal("${after}" "${before}" "descriptor manifest bytes")
expect_no_path("${project_root}/build")

# Manifest lookup follows the supplied path, independently of the caller's cwd.
run_descriptor(ON "project 文😀/./src/../vas-project.json")
expect_json("${descriptor}" "${project_file}" project)
expect_json("${descriptor}" "${project_root}" projectRoot)
file(MAKE_DIRECTORY "${workspace}/other cwd")
set(original_workspace "${workspace}")
set(workspace "${workspace}/other cwd")
run_descriptor(ON "${project_file}")
expect_json("${descriptor}" "${project_file}" project)
set(workspace "${original_workspace}")

# Describing does no entry/config/output filesystem work. Missing paths, invalid
# config text, and an output which is an existing directory remain descriptors.
write_project("${project_file}" absent/source.vas absent/host.txt build/new/deep/bytecode.any)
run_descriptor(ON "${project_file}")
expect_type("${descriptor}" NULL name)
expect_no_path("${project_root}/absent")
expect_no_path("${project_root}/build")
file(WRITE "${project_root}/host/invalid.txt" "invalid host configuration\n")
file(MAKE_DIRECTORY "${project_root}/existing-directory")
write_project("${project_file}" src/main.vas host/invalid.txt existing-directory)
run_descriptor(ON "${project_file}")
expect_no_path("${project_root}/build")

# Legacy values describing tools are strings, never executed or path-validated.
set(legacy "${project_root}/legacy-project.json")
file(SHA256 "${legacy}" before)
run_descriptor(ON "${legacy}")
expect_json("${descriptor}" ON legacyProject)
expect_type("${descriptor}" NULL projectSchemaVersion)
expect_json("${descriptor}" "Legacy contract 文😀" name)
expect_json("${descriptor}" main compilationUnits 0 id)
expect_json("${descriptor}" "${project_root}/src/main.vas" compilationUnits 0 entry)
expect_json("${descriptor}" "${project_root}/host/default.txt" compilationUnits 0 hostApi config)
expect_json("${descriptor}" "${project_root}/build/legacy.vasbc" compilationUnits 0 output)
string(JSON count LENGTH "${descriptor}" compilationUnits)
expect_equal("${count}" 1 "legacy unit count")
string(JSON count LENGTH "${descriptor}" warnings)
expect_equal("${count}" 1 "legacy migration warning count")
expect_json("${descriptor}" legacy_project warnings 0 code)
expect_type("${descriptor}" STRING warnings 0 message)
file(SHA256 "${legacy}" after)
expect_equal("${after}" "${before}" "legacy manifest not rewritten")
expect_no_path("${project_root}/build")

# Every unit is schema-checked, but availability is checked only when building.
project_unit(first main src/main.vas host/default.txt build/main.vasbc)
project_unit(second dormant not-here.vas missing-host.txt dormant/output.vasbc)
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"compilationUnits\":[${first},${second}]}")
run_descriptor(ON "${project_file}")
run_report(ON output ON --project "${project_file}" --unit main)
expect_project_start("${project_file}" main OFF)
expect_no_path("${project_root}/dormant")

# Argument errors still have one machine-readable descriptor, never usage text.
run_descriptor(OFF)
run_descriptor(OFF "${project_file}" unexpected)
run_descriptor(OFF "${project_root}/missing.json")
file(MAKE_DIRECTORY "${project_root}/directory.json")
run_descriptor(OFF "${project_root}/directory.json")
