include("${CMAKE_CURRENT_LIST_DIR}/jsonl_helpers.cmake")
file(MAKE_DIRECTORY "${workspace}/source 文😀" "${workspace}/output 文😀")
file(WRITE "${workspace}/source 文😀/entry 文😀.vas" "void main() {}\n")
set(config "./config.txt")
set(entry "source 文😀/../source 文😀/./entry 文😀.vas")
set(output "output 文😀/./compiled 文😀.vasbc")
run_report(ON output ON "${config}" "${entry}" "${output}")
native_absolute(expected_config "${config}")
native_absolute(expected_output "${output}")
native_absolute(expected_cwd "${workspace}")
expect_json("${record_1}" "${expected_cwd}" cwd)
expect_json("${record_1}" "${expected_config}" config)
expect_json("${record_1}" "${expected_output}" output)
expect_json("${record_1}" "${workspace}/source 文😀/entry 文😀.vas" entry)
find_record(d diagnostic message "Configuration successfully registered")
expect_json("${record_${d}}" "${config}" section)
find_record(d section_loaded section "${workspace}/source 文😀/entry 文😀.vas")
expect_json("${record_${d}}" ON utf8Valid)
find_record(d diagnostic message "Bytecode successfully saved")
expect_json("${record_${d}}" "${output}" section)
file(SIZE "${workspace}/${output}" size)
if(size EQUAL 0)
	message(FATAL_ERROR "Missing bytecode at exact Unicode output path")
endif()

# Backslashes, quotes and controls in callback strings must JSON-roundtrip,
# even where the platform disallows them as real filename characters.
string(ASCII 1 8 9 10 12 13 31 controls)
string(ASCII 92 backslash)
set(strange "missing ${backslash}\"quoted${controls}文😀.as")
run_report(OFF arguments OFF config.txt "${strange}" unused.vasbc)
find_record(d diagnostic severity error)
expect_json("${record_${d}}" "${strange}" section)
expect_json("${record_${d}}" "VAS source files must use the '.vas' extension for the entry script. Received '${strange}'." message)
string(JSON count LENGTH "${record_${d}}" rawBytes)
expect_equal("${count}" 0 "valid UTF-8 control characters")

if(UNIX)
	# POSIX actually permits control/quote filename characters. Source paths
	# deliberately omit backslashes because the existing loader normalizes them.
	set(name "quoted\"${controls}文😀.vas")
	file(WRITE "${workspace}/${name}" "void main() {}\n")
	run_report(ON output ON config.txt "${name}" actual.vasbc)
	expect_json("${record_1}" "${workspace}/${name}" entry)
	find_record(d section_loaded section "${workspace}/${name}")
endif()

# Invalid source bytes are distinct from malformed path text and must not be
# newly rejected, including on Windows/APFS where filenames require Unicode.
string(ASCII 128 192 175 237 160 128 244 144 128 128 194 bad_source)
file(WRITE "${workspace}/invalid-source.vas" "/* ${bad_source} */\nvoid main() {}\n")
run_report(ON output ON config.txt invalid-source.vas out.vasbc)
find_record(d section_loaded section "${workspace}/invalid-source.vas")
expect_json("${record_${d}}" OFF utf8Valid)
string(JSON count LENGTH "${record_${d}}" invalidUtf8Fields)
expect_equal("${count}" 0 "source bytes are not path text fields")
file(WRITE "${workspace}/literal-�.vas" "void main() {}\n")
run_report(ON output ON config.txt literal-�.vas out.vasbc)
expect_json("${record_1}" "${workspace}/literal-�.vas" entry)
string(JSON count LENGTH "${record_1}" invalidUtf8Fields)
expect_equal("${count}" 0 "literal replacement character is valid UTF-8")
