include("${CMAKE_CURRENT_LIST_DIR}/project_helpers.cmake")
project_unit(valid main src/main.vas host/default.txt build/main.vasbc)
set(good "{\"schemaVersion\":1,\"compilationUnits\":[${valid}]}")

foreach(bad IN ITEMS "" "null" "[]" "1" "true" "{}" "{\"schemaVersion\":1}" "{\"compilationUnits\":[]}" "{\"schemaVersion\":1,\"compilationUnits\":[]}")
	run_bad_manifest("${bad}")
endforeach()
foreach(version IN ITEMS 0 2 -1 1.0 1e0 1e400 "\"1\"" null true "{}" "[]")
	run_bad_manifest("{\"schemaVersion\":${version},\"compilationUnits\":[${valid}]}")
endforeach()
foreach(units IN ITEMS null true 1 "{}" "\"main\"" "[null]" "[{}]" "[1]" "[true]" "[\"main\"]")
	run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":${units}}")
endforeach()
foreach(name IN ITEMS null 1 true "{}" "[]")
	run_bad_manifest("{\"schemaVersion\":1,\"name\":${name},\"compilationUnits\":[${valid}]}")
endforeach()
foreach(field IN ITEMS id entry hostApi output)
	string(JSON missing REMOVE "${valid}" ${field})
	run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${missing}]}")
	foreach(value IN ITEMS null 1 true "[]")
		string(JSON changed SET "${valid}" ${field} "${value}")
		run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${changed}]}")
	endforeach()
endforeach()
foreach(host IN ITEMS "{}" "\"host/default.txt\"" "{\"config\":null}" "{\"config\":3}" "{\"config\":\"host/default.txt\",\"extra\":1}")
	run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[{\"id\":\"main\",\"entry\":\"src/main.vas\",\"hostApi\":${host},\"output\":\"build/main.vasbc\"}]}")
endforeach()
string(JSON unknown SET "${good}" typo true)
run_bad_manifest("${unknown}")
expect_json("${descriptor}" 0 errors 0 row)
expect_json("${descriptor}" 0 errors 0 column)
expect_type("${descriptor}" NULL errors 0 byteOffset)
string(JSON unknown SET "${good}" compilationUnits 0 typo true)
run_bad_manifest("${unknown}")
# A valid selected unit cannot hide a malformed unselected unit.
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${valid},{\"id\":\"dormant\"}]}")

# Duplicate members are rejected at every relevant JSON object level, including
# escaped spellings; parsers which silently use the last member cannot pass.
run_bad_manifest("{\"schemaVersion\":1,\"schemaVersion\":1,\"compilationUnits\":[${valid}]}")
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${valid}],\"compilationUnits\":[${valid}]}")
run_bad_manifest([=[{"schemaVersion":1,"compilationUnits":[{"id":"main","\u0069d":"main","entry":"src/main.vas","hostApi":{"config":"host/default.txt"},"output":"build/main.vasbc"}]}]=])
run_bad_manifest([=[{"schemaVersion":1,"compilationUnits":[{"id":"main","entry":"src/main.vas","hostApi":{"config":"host/default.txt","config":"host/default.txt"},"output":"build/main.vasbc"}]}]=])

# IDs are case-sensitive and bounded ASCII identities, not filesystem paths.
foreach(id IN ITEMS "" "." ".." "a/b" "a b" "a:b" "文" "a😀" "a+" "a@")
	project_unit(unit "${id}" src/main.vas host/default.txt build/main.vasbc)
	run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${unit}]}")
endforeach()
string(REPEAT a 65 id)
project_unit(unit "${id}" src/main.vas host/default.txt build/main.vasbc)
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${unit}]}")
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${valid},${valid}]}")
project_unit(same_output another src/main.vas host/default.txt build/main.vasbc)
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${valid},${same_output}]}")
string(REPEAT a 64 id)
project_unit(long_id "${id}" src/main.vas host/default.txt build/a.vasbc)
project_unit(upper Main src/main.vas host/default.txt build/b.vasbc)
project_unit(punctuation _-A.z_0 src/main.vas host/default.txt build/c.vasbc)
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"name\":\"\",\"compilationUnits\":[${valid},${upper},${long_id},${punctuation}]}")
run_descriptor(ON "${project_file}")

# Apply the portable path grammar to every slot, on every operating system.
set(invalid_paths "" "/absolute.vas" "../parent.vas" "./main.vas" "a/../main.vas" "a/./main.vas" "a//main.vas" "a/" "C:/main.vas" "C:main.vas" "//server/share/main.vas" "a\\main.vas" "a:b.vas" "a<b.vas" "a>b.vas" "a|b.vas" "a?b.vas" "a*b.vas" "a\"b.vas" "CON" "con.vas" "PrN.txt" "AUX.vas" "NUL.txt" "COM1.vas" "COM9.vas" "COM¹.vas" "COM².vas" "LPT³.vas" "CONIN$.vas" "CONOUT$.vas" "CLOCK$.vas" "LPT1.vas" "lpt9.vas" "dir/CON.vas" "trailing./main.vas" "trailing /main.vas" "main.vas." "main.vas ")
foreach(path IN LISTS invalid_paths)
	foreach(field IN ITEMS entry config output)
		set(entry src/main.vas)
		set(config host/default.txt)
		set(output build/main.vasbc)
		set(${field} "${path}")
		write_project("${project_file}" "${entry}" "${config}" "${output}")
		file(READ "${project_file}" bad)
		run_bad_manifest("${bad}")
	endforeach()
endforeach()
# Escaped control characters must be rejected after JSON decoding as well.
foreach(escape IN ITEMS "\\u0000" "\\u0001" "\\u0009" "\\u001f" "\\u007f" "\\u0080" "\\u009f")
	foreach(field IN ITEMS entry config output)
		set(entry src/main.vas)
		set(config host/default.txt)
		set(output build/main.vasbc)
		set(${field} "a${escape}b.vas")
		run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[{\"id\":\"main\",\"entry\":\"${entry}\",\"hostApi\":{\"config\":\"${config}\"},\"output\":\"${output}\"}]}")
	endforeach()
endforeach()
foreach(extension IN ITEMS src/main.as src/main.VAS src/main.Vas src/main.vas.txt src/main)
	write_project("${project_file}" "${extension}" host/default.txt build/main.vasbc)
	file(READ "${project_file}" bad)
	run_bad_manifest("${bad}")
endforeach()

# Limits are measured in UTF-8 bytes, not Unicode characters. Description has no
# filesystem availability requirement, so a 4096-byte component is valid here.
string(REPEAT a 4092 long_entry)
string(APPEND long_entry ".vas")
string(REPEAT "😀" 1024 long_config)
string(REPEAT a 4096 long_output)
write_project("${project_file}" "${long_entry}" "${long_config}" "${long_output}")
run_descriptor(ON "${project_file}")
string(REPEAT a 4097 too_long)
write_project("${project_file}" src/main.vas "${too_long}" build/main.vasbc)
file(READ "${project_file}" bad)
run_bad_manifest("${bad}")
string(REPEAT "😀" 1025 too_long)
write_project("${project_file}" src/main.vas "${too_long}" build/main.vasbc)
file(READ "${project_file}" bad)
run_bad_manifest("${bad}")
string(REPEAT "😀" 64 name)
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"name\":\"${name}\",\"compilationUnits\":[${valid}]}")
run_descriptor(ON "${project_file}")
run_bad_manifest("{\"schemaVersion\":1,\"name\":\"${name}a\",\"compilationUnits\":[${valid}]}")

set(units "")
foreach(i RANGE 1 256)
	project_unit(unit "u${i}" absent.vas absent.txt "absent/${i}.vasbc")
	if(NOT units STREQUAL "")
		string(APPEND units ",")
	endif()
	string(APPEND units "${unit}")
endforeach()
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"compilationUnits\":[${units}]}")
run_descriptor(ON "${project_file}")
project_unit(unit u257 absent.vas absent.txt absent/257.vasbc)
run_bad_manifest("{\"schemaVersion\":1,\"compilationUnits\":[${units},${unit}]}")

string(LENGTH "${good}" size)
math(EXPR padding "1048576 - ${size}")
string(REPEAT " " ${padding} pad)
file(WRITE "${project_file}" "${good}${pad}")
run_descriptor(ON "${project_file}")
file(APPEND "${project_file}" " ")
run_descriptor(OFF "${project_file}")
expect_json("${descriptor}" project_limit errors 0 code)
expect_no_path("${project_root}/build")

# Deep unknown content must hit the parser bound before schema evaluation.
set(nested 0)
foreach(i RANGE 1 16)
	set(nested "[${nested}]")
endforeach()
run_bad_manifest("${nested}")
expect_json("${descriptor}" project_schema errors 0 code)
set(nested 0)
foreach(i RANGE 1 17)
	set(nested "[${nested}]")
endforeach()
run_bad_manifest("${nested}")
expect_json("${descriptor}" project_limit errors 0 code)

# Strict JSON grammar, Unicode scalar values, and raw input byte validation.
foreach(bad IN ITEMS "${good} garbage" "${good}${good}" "{\"schemaVersion\":01}" "{\"schemaVersion\":NaN}" "{\"schemaVersion\":1,}" "{/*comment*/\"schemaVersion\":1}" "{\"name\":\"\\uD800\"}" "{\"name\":\"\\uDC00\"}" "{\"name\":\"\\uD800\\u0041\"}" "{\"name\":\"\\x41\"}")
	run_bad_manifest("${bad}")
endforeach()
foreach(bytes IN ITEMS "128" "192;175" "237;160;128" "244;144;128;128" "194")
	string(ASCII ${bytes} invalid)
	run_bad_manifest("{\"name\":\"${invalid}\"}")
	expect_json("${descriptor}" project_encoding errors 0 code)
endforeach()
string(ASCII 1 raw_control)
run_bad_manifest("{\"name\":\"${raw_control}\"}")
# Control the physical newlines explicitly: ordinary file(WRITE) uses the
# host's text mode. Both encodings must report UTF-8 byte positions, counting
# CR in the absolute offset while keeping the second-line column unchanged.
foreach(newline IN ITEMS LF CRLF)
	file(CONFIGURE OUTPUT "${project_file}" CONTENT "{\n\"文\":?}\n"
		@ONLY NEWLINE_STYLE "${newline}")
	file(READ "${project_file}" physical_bytes HEX)
	if(newline STREQUAL "LF")
		expect_equal("${physical_bytes}" "7b0a22e69687223a3f7d0a" "LF manifest bytes")
		set(expected_offset 9)
	else()
		expect_equal("${physical_bytes}" "7b0d0a22e69687223a3f7d0d0a" "CRLF manifest bytes")
		set(expected_offset 10)
	endif()
	run_descriptor(OFF "${project_file}")
	run_report(OFF arguments OFF --project "${project_file}" --unit main)
	expect_count(section_loaded 0)
	expect_no_path("${project_root}/build")
	expect_json("${descriptor}" project_json errors 0 code)
	expect_json("${descriptor}" 2 errors 0 row)
	expect_json("${descriptor}" 7 errors 0 column)
	expect_json("${descriptor}" "${expected_offset}" errors 0 byteOffset)
endforeach()

# Valid paired escapes decode to the same UTF-8 scalar as a literal spelling.
file(WRITE "${project_file}" "{\"schemaVersion\":1,\"name\":\"\\uD83D\\uDE00\",\"compilationUnits\":[${valid}]}")
run_descriptor(ON "${project_file}")
expect_json("${descriptor}" "😀" name)
run_bad_manifest("{")
expect_json("${descriptor}" 1 errors 0 row)
expect_json("${descriptor}" 2 errors 0 column)
expect_json("${descriptor}" 2 errors 0 byteOffset)

# Legacy schema remains strict and uses exactly the same portable path policy.
file(READ "${project_root}/legacy-project.json" legacy)
foreach(field IN ITEMS entry builderConfig bytecodeOutput)
	string(JSON changed SET "${legacy}" ${field} "\"../outside.vas\"")
	run_bad_manifest("${changed}")
	string(JSON changed REMOVE "${legacy}" ${field})
	run_bad_manifest("${changed}")
endforeach()
foreach(field IN ITEMS builder runner)
	string(JSON changed SET "${legacy}" ${field} 17)
	run_bad_manifest("${changed}")
endforeach()
string(JSON changed SET "${legacy}" unknown true)
run_bad_manifest("${changed}")
