include("${CMAKE_CURRENT_LIST_DIR}/jsonl_helpers.cmake")

run_report(OFF config OFF missing-config.txt main.vas out.vasbc)
find_record(d diagnostic severity error)
expect_json("${record_${d}}" missing-config.txt section)
expect_json("${record_${d}}" 0 row)
expect_json("${record_${d}}" 0 column)
expect_count(section_loaded 0)
file(WRITE "${workspace}/bad-config.txt" "typedef Broken \"unknown type\"\n")
run_report(OFF config OFF bad-config.txt main.vas out.vasbc)
find_record(d diagnostic message "Configuration failed")
expect_json("${record_${d}}" bad-config.txt section)
expect_count(section_loaded 0)

run_report(OFF load OFF config.txt missing.vas out.vasbc)
expect_count(section_loaded 0)
find_record(d diagnostic severity error)
expect_json("${record_${d}}" "${workspace}/missing.vas" section)
run_report(OFF arguments OFF missing-config.txt legacy.as out.vasbc)
expect_count(diagnostic 1)
find_record(d diagnostic severity error)
expect_json("${record_${d}}" legacy.as section)
run_report(OFF arguments OFF config.txt upper.VAS out.vasbc)

# A warning is still success. Both warning and error positions count UTF-8
# bytes, not Unicode scalars or UTF-16 code units, including non-BMP text.
set(prefix "void main() { /* 文😀 */ int unused; int value = ")
file(WRITE "${workspace}/warning.vas" "${prefix}unused; }\n")
run_report(ON output ON config.txt warning.vas warning.vasbc)
find_record(d diagnostic severity warning)
string(LENGTH "${prefix}" column)
math(EXPR column "${column} + 1")
expect_json("${record_${d}}" "${workspace}/warning.vas" section)
expect_json("${record_${d}}" 1 row)
expect_json("${record_${d}}" "${column}" column)
find_record(info diagnostic message "Script successfully built")
expect_json("${record_${info}}" warning.vas section)
expect_json("${record_${info}}" 0 row)
expect_json("${record_${info}}" 0 column)

set(prefix "\t/* 文😀 */ ")
file(WRITE "${workspace}/error.vas" "void main() {\r\n${prefix}nonexistent();\r\n}\r\n")
run_report(OFF compile ON config.txt error.vas failed.vasbc)
find_record(d diagnostic message "No matching symbol 'nonexistent'")
string(LENGTH "${prefix}" column)
math(EXPR column "${column} + 1")
expect_json("${record_${d}}" "${workspace}/error.vas" section)
expect_json("${record_${d}}" 2 row)
expect_json("${record_${d}}" "${column}" column)
if(EXISTS "${workspace}/failed.vasbc")
	message(FATAL_ERROR "Compilation failure wrote bytecode")
endif()
file(WRITE "${workspace}/empty.vas" "")
run_report(OFF compile ON config.txt empty.vas failed.vasbc)
expect_count(section_loaded 1)
find_record(d section_loaded section "${workspace}/empty.vas")
expect_json("${record_${d}}" ON utf8Valid)
