include("${CMAKE_CURRENT_LIST_DIR}/project_helpers.cmake")

# Unit selection determines config/output even when entries are identical.
run_report(ON output ON --project "${project_file}" --unit main)
expect_project_start("${project_file}" main OFF)
expect_json("${record_1}" "${project_root}/src/main.vas" entry)
expect_json("${record_1}" "${project_root}/host/default.txt" config)
expect_json("${record_1}" "${project_root}/build/main.vasbc" output)
expect_count(section_loaded 1)
file(SIZE "${project_root}/build/main.vasbc" size)
if(size LESS 1)
	message(FATAL_ERROR "Project compilation produced empty bytecode")
endif()
file(WRITE "${project_root}/build/other.vasbc" "retain failed-unit output")
run_report(OFF compile ON --project "${project_file}" --unit other-host)
expect_project_start("${project_file}" other-host OFF)
expect_json("${record_1}" "${project_root}/src/main.vas" entry)
expect_json("${record_1}" "${project_root}/host/alternate.txt" config)
expect_file_text("${project_root}/build/other.vasbc" "retain failed-unit output")

# An external working directory never becomes the project's resolution root.
set(original_workspace "${workspace}")
file(MAKE_DIRECTORY "${workspace}/unrelated cwd")
set(workspace "${workspace}/unrelated cwd")
run_report(ON output ON --project "${project_file}" --unit main)
expect_project_start("${project_file}" main OFF)
expect_json("${record_1}" "${project_root}/src/main.vas" entry)
set(workspace "${original_workspace}")
run_report(ON output ON --project "project 文😀/./src/../vas-project.json" --unit main)
expect_project_start("${project_file}" main OFF)

# Shell metacharacters are ordinary portable filename characters. No shell or
# environment substitution is involved in either JSON paths or argv transport.
set(meta "文😀 space $dollar ; & (group) `tick`")
file(MAKE_DIRECTORY "${project_root}/${meta}")
file(WRITE "${project_root}/${meta}/main.vas" "void main() {}\n")
file(WRITE "${project_root}/${meta}/host.txt" "// Empty host API\n")
set(meta_manifest "${project_root}/${meta}/manifest.json")
write_project("${meta_manifest}" main.vas host.txt "new dir/${meta}.data")
run_descriptor(ON "${meta_manifest}")
expect_json("${descriptor}" "${project_root}/${meta}/new dir/${meta}.data" compilationUnits 0 output)
run_project_report(ON output ON "${meta_manifest}" main)
expect_project_start("${meta_manifest}" main OFF)
expect_json("${record_1}" "${project_root}/${meta}/main.vas" entry)
if(NOT EXISTS "${project_root}/${meta}/new dir/${meta}.data")
	message(FATAL_ERROR "Literal metacharacter output was not written")
endif()
expect_no_path("${project_root}/must-not-run")

# Legacy normalization selects the native path contract with one migration
# warning and produces the same bytecode as v1 for equivalent input slots.
set(legacy "${project_root}/legacy-project.json")
file(SHA256 "${legacy}" before)
run_report(ON output ON --project "${legacy}" --unit main)
expect_project_start("${legacy}" main ON)
expect_json("${record_1}" "${project_root}/src/main.vas" entry)
set(warnings 0)
foreach(i RANGE 1 ${report_count})
	string(JSON type GET "${record_${i}}" type)
	if(type STREQUAL "diagnostic")
		string(JSON severity GET "${record_${i}}" severity)
		if(severity STREQUAL "warning")
			math(EXPR warnings "${warnings} + 1")
		endif()
	endif()
endforeach()
expect_equal("${warnings}" 1 "legacy build migration warning count")
file(SHA256 "${legacy}" after)
expect_equal("${after}" "${before}" "legacy build does not rewrite manifest")
file(SHA256 "${project_root}/build/main.vasbc" v1_hash)
file(SHA256 "${project_root}/build/legacy.vasbc" legacy_hash)
expect_equal("${legacy_hash}" "${v1_hash}" "legacy and v1 bytecode equivalence")

# All project invocation forms require an explicit, exact unit selection, even
# after narrowing to a manifest with only one possible unit.
write_project("${project_file}" src/main.vas host/default.txt build/main.vasbc)
run_report(OFF arguments OFF --project "${project_file}")
run_report(OFF arguments OFF --project "${project_file}" --unit)
run_report(OFF arguments OFF --project "${project_file}" --unit nonexistent)
run_report(OFF arguments OFF --project "${project_file}" --unit MAIN)
run_report(OFF arguments OFF --project "${project_file}" --unit main extra)
run_report(OFF arguments OFF --project)
run_report(OFF arguments OFF --unit main --project "${project_file}")
run_report(OFF arguments OFF --project "${project_file}" --unit main --unit main)
run_report(OFF arguments OFF --project "${project_file}" --unit main --project "${project_file}")
run_report(OFF arguments OFF --project "${project_root}/missing.json" --unit main)

# Selected missing inputs fail before any output directory is created.
write_project("${project_file}" missing.vas host/default.txt absent/deep/out.vasbc)
run_report(OFF load OFF --project "${project_file}" --unit main)
expect_count(section_loaded 0)
expect_no_path("${project_root}/absent")
write_project("${project_file}" src/main.vas missing.txt absent/deep/out.vasbc)
run_report(OFF config OFF --project "${project_file}" --unit main)
expect_count(section_loaded 0)
expect_no_path("${project_root}/absent")

# The original positional reporting contract is still usable and byte-identical.
run_report(ON output ON "${project_root}/host/default.txt" "${project_root}/src/main.vas" "${project_root}/build/positional.vasbc")
file(SHA256 "${project_root}/build/positional.vasbc" positional_hash)
expect_equal("${positional_hash}" "${v1_hash}" "project and positional bytecode equivalence")
execute_process(COMMAND "${VASBUILD}" "${project_root}/host/default.txt" "${project_root}/src/main.vas" "${project_root}/build/default.vasbc" tolerated-extra
	WORKING_DIRECTORY "${workspace}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING NONE TIMEOUT 20)
expect_equal("${result}" 0 "unchanged positional CLI trailing-argument tolerance")
file(SHA256 "${project_root}/build/default.vasbc" default_hash)
expect_equal("${default_hash}" "${v1_hash}" "project and default bytecode equivalence")
