include("${CMAKE_CURRENT_LIST_DIR}/jsonl_helpers.cmake")
if(NOT UNIX)
	message(FATAL_ERROR "Invalid native filename byte fixtures require POSIX")
endif()

# Independent byte construction exercises isolated continuations, overlongs,
# surrogates, values above U+10FFFF, and truncated multibyte sequences.
string(ASCII 128 192 175 237 160 128 244 144 128 128 194 bad)
string(REPEAT "�" 11 replacement)
# APFS accepts only valid UTF-8 filenames. Keep malformed-argument diagnostics
# below on Apple, but create malformed names only on byte-oriented filesystems.
# https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html
if(NOT APPLE)
	set(name "bad-${bad}.vas")
	file(WRITE "${workspace}/${name}" "void main() {}\n")
	run_report(ON output ON config.txt "${name}" out.vasbc)
	string(HEX "${workspace}/${name}" raw)
	expect_json("${record_1}" "${workspace}/bad-${replacement}.vas" entry)
	expect_json("${record_1}" entry invalidUtf8Fields 0)
	expect_json("${record_1}" "${raw}" rawBytes entry)
	find_record(d section_loaded section "${workspace}/bad-${replacement}.vas")
	expect_json("${record_${d}}" ON utf8Valid)
	expect_json("${record_${d}}" section invalidUtf8Fields 0)
	expect_json("${record_${d}}" "${raw}" rawBytes section)

endif()

# Missing-file diagnostics echo the malformed path in both section and message.
set(name "missing-${bad}.vas")
run_report(OFF load OFF config.txt "${name}" out.vasbc)
find_record(d diagnostic severity error)
set(section "${workspace}/${name}")
string(HEX "${section}" raw_section)
string(HEX "Failed to open script file '${section}'" raw_message)
expect_json("${record_${d}}" "${workspace}/missing-${replacement}.vas" section)
expect_json("${record_${d}}" "Failed to open script file '${workspace}/missing-${replacement}.vas'" message)
expect_json("${record_${d}}" section invalidUtf8Fields 0)
expect_json("${record_${d}}" message invalidUtf8Fields 1)
expect_json("${record_${d}}" "${raw_section}" rawBytes section)
expect_json("${record_${d}}" "${raw_message}" rawBytes message)

if(NOT APPLE)
	# Two byte-distinct paths may have identical display strings but remain distinct
	# through rawBytes, including config/output and the process working directory.
	string(ASCII 254 first)
	string(ASCII 255 second)
	set(original_workspace "${workspace}")
	set(workspace "${workspace}/cwd-${first}")
	file(MAKE_DIRECTORY "${workspace}")
	file(WRITE "${workspace}/config-${first}.txt" "// host\n")
	file(WRITE "${workspace}/main.vas" "void main() {}\n")
	run_report(ON output ON "config-${first}.txt" main.vas "out-${second}.vasbc")
	foreach(field cwd config output)
		if(field STREQUAL "cwd")
			set(value "${workspace}")
		elseif(field STREQUAL "config")
			set(value "${workspace}/config-${first}.txt")
		else()
			set(value "${workspace}/out-${second}.vasbc")
		endif()
		string(HEX "${value}" raw)
		expect_json("${record_1}" "${raw}" rawBytes ${field})
	endforeach()
	set(workspace "${original_workspace}")

	# Include callbacks expose all three identity-bearing byte strings. Distinct
	# malformed tokens display alike, but their lossless identities cannot collide.
	foreach(byte IN ITEMS "${first}" "${second}")
		set(entry "entry-${byte}.vas")
		set(included "shared-${byte}.vas")
		file(WRITE "${workspace}/${entry}" "#include \"${included}\"\nvoid main() {}\n")
		file(WRITE "${workspace}/${included}" "")
		run_report(ON output ON config.txt "${entry}" out.vasbc)
		find_record(a include_attempt requested "shared-�.vas")
		expect_json("${record_${a}}" "${workspace}/entry-�.vas" from)
		expect_json("${record_${a}}" "${workspace}/shared-�.vas" resolved)
		string(HEX "${workspace}/${entry}" raw_from)
		string(HEX "${included}" raw_requested)
		string(HEX "${workspace}/${included}" raw_resolved)
		expect_json("${record_${a}}" "${raw_from}" rawBytes from)
		expect_json("${record_${a}}" "${raw_requested}" rawBytes requested)
		expect_json("${record_${a}}" "${raw_resolved}" rawBytes resolved)
		find_record(r include_result attemptSeq "${a}")
		expect_json("${record_${r}}" loaded status)
	endforeach()
endif()
