cmake_minimum_required(VERSION 3.21)

foreach(required VASBUILD TEST_ROOT)
	if(NOT DEFINED ${required})
		message(FATAL_ERROR "Missing -D${required}=... for JSONL conformance tests")
	endif()
endforeach()
set(workspace "${TEST_ROOT}/workspace 文😀")
file(MAKE_DIRECTORY "${workspace}")
file(WRITE "${workspace}/config.txt" "// Empty host interface\n")
file(WRITE "${workspace}/main.vas" "void main() {}\n")

function(expect_equal actual expected label)
	if(NOT "${actual}" STREQUAL "${expected}")
		message(FATAL_ERROR "${label}: expected [${expected}], got [${actual}]")
	endif()
endfunction()

function(expect_json json expected)
	string(JSON actual ERROR_VARIABLE error GET "${json}" ${ARGN})
	if(error)
		message(FATAL_ERROR "Missing/invalid JSON field ${ARGN}: ${error}\n${json}")
	endif()
	expect_equal("${actual}" "${expected}" "JSON field ${ARGN}")
endfunction()

function(expect_type json expected)
	string(JSON actual ERROR_VARIABLE error TYPE "${json}" ${ARGN})
	if(error OR NOT actual STREQUAL expected)
		message(FATAL_ERROR "Expected ${expected} at ${ARGN}, got ${actual}: ${error}\n${json}")
	endif()
endfunction()

# JSON parsers can be permissive about raw malformed UTF-8. Independently
# consume only scalar-value encodings, including the overlong/surrogate limits.
function(expect_utf8 text)
	string(HEX "${text}" hex)
	set(continuation "[89ab][0-9a-f]")
	set(scalar "[0-7][0-9a-f]|(c[2-9a-f]|d[0-9a-f])${continuation}")
	string(APPEND scalar "|e0[ab][0-9a-f]${continuation}|e[1-9abcef]${continuation}${continuation}|ed[89][0-9a-f]${continuation}")
	string(APPEND scalar "|f0[9ab][0-9a-f]${continuation}${continuation}|f[1-3]${continuation}${continuation}${continuation}|f48[0-9a-f]${continuation}${continuation}")
	string(REGEX REPLACE "${scalar}" "" residue "${hex}")
	if(NOT residue STREQUAL "")
		message(FATAL_ERROR "Report contains invalid UTF-8 bytes: ${residue}")
	endif()
endfunction()

function(parse_report text)
	expect_utf8("${text}")
	if(NOT text MATCHES "\n$")
		message(FATAL_ERROR "Report must end with a newline: ${text}")
	endif()
	set(remaining "${text}")
	set(count 0)
	set(start_count 0)
	set(result_count 0)
	set(pending_attempts "")
	while(NOT remaining STREQUAL "")
		string(FIND "${remaining}" "\n" end)
		string(SUBSTRING "${remaining}" 0 ${end} record)
		math(EXPR next "${end} + 1")
		string(SUBSTRING "${remaining}" ${next} -1 remaining)
		math(EXPR count "${count} + 1")
		expect_type("${record}" OBJECT)
		expect_json("${record}" vasbuild protocol)
		expect_type("${record}" NUMBER version)
		expect_json("${record}" 1 version)
		expect_type("${record}" NUMBER seq)
		expect_json("${record}" "${count}" seq)
		expect_type("${record}" STRING type)
		expect_type("${record}" ARRAY invalidUtf8Fields)
		expect_type("${record}" OBJECT rawBytes)
		string(JSON invalid_count LENGTH "${record}" invalidUtf8Fields)
		string(JSON raw_count LENGTH "${record}" rawBytes)
		expect_equal("${invalid_count}" "${raw_count}" "rawBytes field count")
		if(invalid_count GREATER 0)
			math(EXPR last_invalid "${invalid_count} - 1")
			foreach(i RANGE 0 ${last_invalid})
				expect_type("${record}" STRING invalidUtf8Fields ${i})
				string(JSON field GET "${record}" invalidUtf8Fields ${i})
				expect_type("${record}" STRING "${field}")
				expect_type("${record}" STRING rawBytes "${field}")
				string(JSON raw GET "${record}" rawBytes "${field}")
				if(NOT raw MATCHES "^([0-9a-f][0-9a-f])+$")
					message(FATAL_ERROR "rawBytes.${field} is not lowercase whole-byte hex: ${raw}")
				endif()
			endforeach()
		endif()
		string(JSON type GET "${record}" type)
		if(type STREQUAL "start")
			math(EXPR start_count "${start_count} + 1")
			expect_equal("${count}" 1 "start position")
			expect_json("${record}" vasbuild compiler)
			expect_type("${record}" STRING compilerVersion)
			string(JSON compiler_version GET "${record}" compilerVersion)
			if(compiler_version STREQUAL "")
				message(FATAL_ERROR "compilerVersion must not be empty")
			endif()
			expect_json("${record}" utf-8-bytes positionEncoding)
			expect_type("${record}" NUMBER positionBase)
			expect_json("${record}" 1 positionBase)
			foreach(field cwd config entry output)
				string(JSON path_type TYPE "${record}" ${field})
				if(NOT path_type MATCHES "^(STRING|NULL)$")
					message(FATAL_ERROR "start.${field} must be a string or null")
				endif()
				if(path_type STREQUAL "STRING")
					string(JSON path GET "${record}" ${field})
					if(NOT IS_ABSOLUTE "${path}")
						message(FATAL_ERROR "start.${field} is not absolute: ${path}")
					endif()
				endif()
			endforeach()
		elseif(type STREQUAL "diagnostic")
			foreach(field severity section message)
				expect_type("${record}" STRING ${field})
			endforeach()
			string(JSON severity GET "${record}" severity)
			if(NOT severity MATCHES "^(information|warning|error)$")
				message(FATAL_ERROR "Unknown diagnostic severity: ${severity}")
			endif()
			foreach(field row column)
				expect_type("${record}" NUMBER ${field})
				string(JSON position GET "${record}" ${field})
				if(NOT position MATCHES "^[0-9]+$")
					message(FATAL_ERROR "Invalid diagnostic ${field}: ${position}")
				endif()
			endforeach()
		elseif(type STREQUAL "section_loaded")
			expect_type("${record}" STRING section)
			expect_type("${record}" BOOLEAN utf8Valid)
			string(JSON digest_version ERROR_VARIABLE no_digest GET "${record}" sourceDigestVersion)
			if(NOT no_digest)
				expect_type("${record}" NUMBER sourceDigestVersion)
				expect_json("${record}" 1 sourceDigestVersion)
				expect_type("${record}" STRING sourceDigestAlgorithm)
				expect_json("${record}" sha256 sourceDigestAlgorithm)
				expect_type("${record}" NUMBER sourceByteLength)
				string(JSON size GET "${record}" sourceByteLength)
				if(NOT size MATCHES "^[0-9]+$" OR size GREATER 2147483647)
					message(FATAL_ERROR "Invalid source byte length: ${size}")
				endif()
				expect_type("${record}" STRING sourceDigest)
				string(JSON digest GET "${record}" sourceDigest)
				string(LENGTH "${digest}" digest_length)
				if(NOT digest_length EQUAL 64 OR NOT digest MATCHES "^[0-9a-f]+$")
					message(FATAL_ERROR "Invalid lowercase SHA-256 digest: ${digest}")
				endif()
			else()
				foreach(field sourceDigestAlgorithm sourceByteLength sourceDigest)
					string(JSON unused ERROR_VARIABLE absent GET "${record}" "${field}")
					if(NOT absent)
						message(FATAL_ERROR "Partial digest contract: ${record}")
					endif()
				endforeach()
			endif()
		elseif(type STREQUAL "include_attempt")
			expect_type("${record}" STRING from)
			expect_type("${record}" STRING requested)
			string(JSON resolved_type TYPE "${record}" resolved)
			if(NOT resolved_type MATCHES "^(STRING|NULL)$")
				message(FATAL_ERROR "include_attempt.resolved must be a string or null")
			endif()
			list(APPEND pending_attempts "${count}")
		elseif(type STREQUAL "include_result")
			expect_type("${record}" NUMBER attemptSeq)
			expect_type("${record}" STRING status)
			string(JSON attempt GET "${record}" attemptSeq)
			string(JSON status GET "${record}" status)
			if(NOT status MATCHES "^(loaded|skipped|failed|rejected)$")
				message(FATAL_ERROR "Unknown include status: ${status}")
			endif()
			if(NOT pending_attempts)
				message(FATAL_ERROR "include_result has no outstanding attempt: ${record}")
			endif()
			list(POP_BACK pending_attempts expected_attempt)
			expect_equal("${attempt}" "${expected_attempt}" "nested include correlation")
		elseif(type STREQUAL "result")
			math(EXPR result_count "${result_count} + 1")
			expect_type("${record}" BOOLEAN success)
			expect_type("${record}" BOOLEAN dependenciesComplete)
			expect_type("${record}" STRING phase)
			string(JSON phase GET "${record}" phase)
			if(NOT phase MATCHES "^(arguments|engine|config|load|compile|output)$")
				message(FATAL_ERROR "Unknown result phase: ${phase}")
			endif()
			if(NOT remaining STREQUAL "")
				message(FATAL_ERROR "result is not the last record")
			endif()
		else()
			message(FATAL_ERROR "Unknown record type: ${type}")
		endif()
		set(record_${count} "${record}" PARENT_SCOPE)
	endwhile()
	expect_equal("${start_count}" 1 "start count")
	expect_equal("${result_count}" 1 "terminal result count")
	expect_equal("${pending_attempts}" "" "unmatched include attempts")
	set(report_count "${count}" PARENT_SCOPE)
endfunction()

function(run_report success phase complete)
	execute_process(COMMAND "${VASBUILD}" --report=jsonl ${ARGN}
		WORKING_DIRECTORY "${workspace}" RESULT_VARIABLE result
		OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING NONE TIMEOUT 20)
	if((success AND NOT "${result}" STREQUAL "0") OR (NOT success AND "${result}" STREQUAL "0"))
		message(FATAL_ERROR "Unexpected exit status ${result}; expected success=${success}\n${out}\n${err}")
	endif()
	expect_equal("${err}" "" "report stderr")
	parse_report("${out}")
	expect_json("${record_${report_count}}" "${success}" success)
	expect_json("${record_${report_count}}" "${phase}" phase)
	expect_json("${record_${report_count}}" "${complete}" dependenciesComplete)
	foreach(i RANGE 1 ${report_count})
		set(record_${i} "${record_${i}}" PARENT_SCOPE)
	endforeach()
	set(report_count "${report_count}" PARENT_SCOPE)
	set(report_text "${out}" PARENT_SCOPE)
endfunction()

function(find_record output type field expected)
	foreach(i RANGE 1 ${report_count})
		string(JSON actual_type GET "${record_${i}}" type)
		if(actual_type STREQUAL type)
			string(JSON actual GET "${record_${i}}" "${field}")
			if("${actual}" STREQUAL "${expected}")
				set(${output} "${i}" PARENT_SCOPE)
				return()
			endif()
		endif()
	endforeach()
	message(FATAL_ERROR "Missing ${type} with ${field}=[${expected}]\n${report_text}")
endfunction()

function(expect_count type expected)
	set(count 0)
	foreach(i RANGE 1 ${report_count})
		string(JSON actual_type GET "${record_${i}}" type)
		if(actual_type STREQUAL type)
			math(EXPR count "${count} + 1")
		endif()
	endforeach()
	expect_equal("${count}" "${expected}" "${type} count")
endfunction()

# Native absolute config/output paths differ from normalized source identities.
function(native_absolute output relative)
	if(IS_ABSOLUTE "${relative}")
		set(path "${relative}")
	else()
		set(path "${workspace}/${relative}")
	endif()
	if(WIN32)
		cmake_path(NORMAL_PATH path)
		string(REPLACE "/" "\\" path "${path}")
	endif()
	set(${output} "${path}" PARENT_SCOPE)
endfunction()
