include("${CMAKE_CURRENT_LIST_DIR}/jsonl_helpers.cmake")

# Every script owns its TEST_ROOT. Repeated CTest runs start with the same inputs.
file(REMOVE_RECURSE "${workspace}")
file(MAKE_DIRECTORY "${workspace}")
set(project_root "${workspace}/project 文😀")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/project-contract/" DESTINATION "${project_root}")
set(project_file "${project_root}/vas-project.json")
file(WRITE "${workspace}/config.txt" "// Empty host interface\n")
file(WRITE "${workspace}/main.vas" "void main() {}\n")

function(json_quote output value)
	string(REPLACE "\\" "\\\\" value "${value}")
	string(REPLACE "\"" "\\\"" value "${value}")
	string(REPLACE "\n" "\\n" value "${value}")
	string(REPLACE "\r" "\\r" value "${value}")
	string(REPLACE "\t" "\\t" value "${value}")
	set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(project_unit output id entry config destination)
	json_quote(jid "${id}")
	json_quote(jentry "${entry}")
	json_quote(jconfig "${config}")
	json_quote(joutput "${destination}")
	set(${output} "{\"id\":${jid},\"entry\":${jentry},\"hostApi\":{\"config\":${jconfig}},\"output\":${joutput}}" PARENT_SCOPE)
endfunction()

function(write_project manifest entry config destination)
	project_unit(unit main "${entry}" "${config}" "${destination}")
	file(WRITE "${manifest}" "{\"schemaVersion\":1,\"compilationUnits\":[${unit}]}\n")
endfunction()

function(parse_descriptor text success)
	expect_utf8("${text}")
	if(NOT text MATCHES "\n$" OR text MATCHES "\r")
		message(FATAL_ERROR "Descriptor must end with LF and contain no raw CR: ${text}")
	endif()
	string(REGEX MATCHALL "\n" newlines "${text}")
	list(LENGTH newlines newline_count)
	expect_equal("${newline_count}" 1 "descriptor physical line count")
	expect_type("${text}" OBJECT)
	expect_json("${text}" vas-project protocol)
	expect_type("${text}" NUMBER version)
	expect_json("${text}" 1 version)
	expect_type("${text}" BOOLEAN success)
	expect_json("${text}" "${success}" success)
	foreach(field project projectRoot name)
		string(JSON type TYPE "${text}" ${field})
		if(NOT type MATCHES "^(STRING|NULL)$")
			message(FATAL_ERROR "Descriptor ${field} must be string or null")
		endif()
	endforeach()
	foreach(field project projectRoot)
		string(JSON type TYPE "${text}" ${field})
		if(type STREQUAL "STRING")
			string(JSON path GET "${text}" ${field})
			if(NOT IS_ABSOLUTE "${path}" OR path MATCHES "\\\\")
				message(FATAL_ERROR "Descriptor ${field} must be absolute with forward slashes: ${path}")
			endif()
			set(normalized "${path}")
			cmake_path(NORMAL_PATH normalized)
			expect_equal("${path}" "${normalized}" "descriptor lexical normalization")
		endif()
	endforeach()
	string(JSON type TYPE "${text}" projectSchemaVersion)
	if(NOT type MATCHES "^(NUMBER|NULL)$")
		message(FATAL_ERROR "projectSchemaVersion must be number or null")
	endif()
	expect_type("${text}" BOOLEAN legacyProject)
	foreach(field compilationUnits warnings errors)
		expect_type("${text}" ARRAY ${field})
	endforeach()
	string(JSON units LENGTH "${text}" compilationUnits)
	string(JSON errors LENGTH "${text}" errors)
	if(success)
		expect_equal("${errors}" 0 "successful descriptor errors")
		string(JSON legacy GET "${text}" legacyProject)
		if(legacy)
			expect_type("${text}" NULL projectSchemaVersion)
		else()
			expect_json("${text}" 1 projectSchemaVersion)
		endif()
		if(units LESS 1)
			message(FATAL_ERROR "Successful descriptor must contain a compilation unit")
		endif()
		math(EXPR last "${units} - 1")
		foreach(i RANGE 0 ${last})
			expect_type("${text}" OBJECT compilationUnits ${i})
			expect_type("${text}" STRING compilationUnits ${i} id)
			expect_type("${text}" OBJECT compilationUnits ${i} hostApi)
			foreach(slot IN ITEMS entry output)
				expect_type("${text}" STRING compilationUnits ${i} ${slot})
				string(JSON path GET "${text}" compilationUnits ${i} ${slot})
				if(NOT IS_ABSOLUTE "${path}" OR path MATCHES "\\\\")
					message(FATAL_ERROR "Descriptor unit ${slot} is not absolute forward-slash identity: ${path}")
				endif()
			endforeach()
			expect_type("${text}" STRING compilationUnits ${i} hostApi config)
			string(JSON path GET "${text}" compilationUnits ${i} hostApi config)
			if(NOT IS_ABSOLUTE "${path}" OR path MATCHES "\\\\")
				message(FATAL_ERROR "Descriptor unit config is not absolute forward-slash identity: ${path}")
			endif()
		endforeach()
	else()
		expect_equal("${units}" 0 "failed descriptor must expose no units")
		if(errors LESS 1)
			message(FATAL_ERROR "Failed descriptor must contain errors: ${text}")
		endif()
		math(EXPR last "${errors} - 1")
		foreach(i RANGE 0 ${last})
			foreach(field code field message section)
				expect_type("${text}" STRING errors ${i} ${field})
			endforeach()
			foreach(field code message)
				string(JSON value GET "${text}" errors ${i} ${field})
				if(value STREQUAL "")
					message(FATAL_ERROR "Error ${field} must be useful: ${text}")
				endif()
			endforeach()
			foreach(field row column)
				expect_type("${text}" NUMBER errors ${i} ${field})
				string(JSON value GET "${text}" errors ${i} ${field})
				if(NOT value MATCHES "^[0-9]+$")
					message(FATAL_ERROR "Error ${field} is not a nonnegative integer")
				endif()
			endforeach()
			string(JSON type TYPE "${text}" errors ${i} byteOffset)
			if(NOT type MATCHES "^(NUMBER|NULL)$")
				message(FATAL_ERROR "Error byteOffset must be integer or null")
			endif()
		endforeach()
	endif()
	set(descriptor "${text}" PARENT_SCOPE)
endfunction()

function(run_descriptor success)
	# Preserve semicolons in individual argv slots instead of flattening ARGN.
	set(arguments "")
	math(EXPR last "${ARGC} - 1")
	if(last GREATER_EQUAL 1)
		foreach(i RANGE 1 ${last})
			string(REPLACE ";" "\\;" argument "${ARGV${i}}")
			list(APPEND arguments "${argument}")
		endforeach()
	endif()
	execute_process(COMMAND "${VASBUILD}" --describe-project=json ${arguments}
		WORKING_DIRECTORY "${workspace}" RESULT_VARIABLE result
		OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING NONE TIMEOUT 20)
	if((success AND NOT "${result}" STREQUAL "0") OR (NOT success AND "${result}" STREQUAL "0"))
		message(FATAL_ERROR "Unexpected descriptor exit ${result}; expected success=${success}\n${out}\n${err}")
	endif()
	expect_equal("${err}" "" "descriptor stderr")
	parse_descriptor("${out}" "${success}")
	set(descriptor "${descriptor}" PARENT_SCOPE)
endfunction()

function(expect_no_path path)
	if(EXISTS "${path}" OR IS_SYMLINK "${path}")
		message(FATAL_ERROR "Unexpected filesystem side effect: ${path}")
	endif()
endfunction()

function(expect_file_text path expected)
	file(READ "${path}" actual)
	expect_equal("${actual}" "${expected}" "preserved ${path}")
endfunction()

function(expect_project_start manifest unit legacy)
	expect_json("${record_1}" "${manifest}" project)
	if(legacy)
		expect_type("${record_1}" NULL projectSchemaVersion)
	else()
		expect_json("${record_1}" 1 projectSchemaVersion)
	endif()
	expect_json("${record_1}" "${unit}" unit)
	expect_json("${record_1}" "${legacy}" legacyProject)
endfunction()

function(run_bad_manifest contents)
	file(WRITE "${project_file}" "${contents}")
	run_descriptor(OFF "${project_file}")
	run_report(OFF arguments OFF --project "${project_file}" --unit main)
	expect_count(section_loaded 0)
	expect_no_path("${project_root}/build")
	set(descriptor "${descriptor}" PARENT_SCOPE)
endfunction()

# Fixed project argument slots also preserve shell-valid semicolons literally.
function(run_project_report success phase complete manifest unit)
	execute_process(COMMAND "${VASBUILD}" --report=jsonl --project "${manifest}" --unit "${unit}"
		WORKING_DIRECTORY "${workspace}" RESULT_VARIABLE result
		OUTPUT_VARIABLE out ERROR_VARIABLE err ENCODING NONE TIMEOUT 20)
	if((success AND NOT "${result}" STREQUAL "0") OR (NOT success AND "${result}" STREQUAL "0"))
		message(FATAL_ERROR "Unexpected exit status ${result}; expected success=${success}\n${out}\n${err}")
	endif()
	expect_equal("${err}" "" "project report stderr")
	parse_report("${out}")
	expect_json("${record_${report_count}}" "${success}" success)
	expect_json("${record_${report_count}}" "${phase}" phase)
	expect_json("${record_${report_count}}" "${complete}" dependenciesComplete)
	foreach(i RANGE 1 ${report_count})
		set(record_${i} "${record_${i}}" PARENT_SCOPE)
	endforeach()
	set(report_count "${report_count}" PARENT_SCOPE)
	set(report_text "${out}" PARENT_SCOPE)
endfunction()
