'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const vscode = require('vscode');

async function run() {
  const root = path.resolve(__dirname, '../../..'), entry = path.join(root, 'examples/arena/main.vas');
  const extension = vscode.extensions.getExtension('VerseAngelScript.verseangelscript-vscode');
  assert(extension); await extension.activate();
  const document = await vscode.workspace.openTextDocument(entry);
  await vscode.window.showTextDocument(document);
  assert.equal(document.languageId, 'vas');
  const position = text => document.positionAt(document.getText().indexOf(text));
  const definitions = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', document.uri, position('RunDemo('));
  assert.equal(definitions.length, 1); assert.equal(path.basename(definitions[0].uri.fsPath), 'Demo.vas');
  const imported = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', document.uri, position('Arena.Demo'));
  assert.equal(path.basename(imported[0].uri.fsPath), 'Demo.vas');
  const completion = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, position('RunDemo('));
  assert(completion.items.some(item => item.label === 'RunDemo'));
  assert(completion.items.some(item => item.label === 'RunBatch'));
  assert(!completion.items.some(item => item.label === 'VAS_ARENA_MAX_ROUNDS'), 'namespace completion must exclude global macros');
  const unqualified = await vscode.commands.executeCommand('vscode.executeCompletionItemProvider', document.uri, position('return 0;'));
  assert(unqualified.items.some(item => item.label === 'VAS_ARENA_MAX_ROUNDS'));
  assert(unqualified.items.some(item => item.label === 'println'));
  const symbols = await vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', document.uri);
  assert(symbols.some(symbol => symbol.name === 'main'));
  const hover = await vscode.commands.executeCommand('vscode.executeHoverProvider', document.uri, position('RunDemo('));
  assert(hover.length > 0);
  const legend = await vscode.commands.executeCommand('vscode.provideDocumentSemanticTokensLegend', document.uri);
  const semantic = await vscode.commands.executeCommand('vscode.provideDocumentSemanticTokens', document.uri);
  assert(legend.tokenTypes.includes('macro')); assert(semantic.data.length >= 5);
  const combatant = await vscode.workspace.openTextDocument(path.join(root, 'examples/arena/Arena/Combatant.vas'));
  const role = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', combatant.uri, combatant.positionAt(combatant.getText().indexOf('Warrior, 90')));
  assert.equal(role.length, 1); assert.equal(path.basename(role[0].uri.fsPath), 'Combatant.vas');
  assert(role[0].range.start.line < combatant.positionAt(combatant.getText().indexOf('Warrior, 90')).line);
  const demo = await vscode.workspace.openTextDocument(definitions[0].uri), before = demo.getText();
  const edit = new vscode.WorkspaceEdit();
  const start = before.indexOf('RunDemo(');
  edit.replace(demo.uri, new vscode.Range(demo.positionAt(start), demo.positionAt(start + 7)), 'RunChangedDemo');
  assert(await vscode.workspace.applyEdit(edit));
  const after = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', document.uri, position('RunDemo('));
  assert.equal(after.length, 0, 'unsaved imported source must invalidate navigation');
  await vscode.window.showTextDocument(demo); await vscode.commands.executeCommand('workbench.action.files.revert');
  const restored = await vscode.commands.executeCommand('vscode.executeDefinitionProvider', document.uri, position('RunDemo('));
  assert.equal(restored.length, 1);
  const evidence = { version: vscode.version, files: 9, definition: 'Arena/Demo.vas:RunDemo', importNavigation: true, completion: true, macros: true, documentSymbols: true, hover: true, semanticTokens: semantic.data.length / 5, unsavedInvalidation: true, enumNavigation: true };
  if (process.env.VAS_LANGUAGE_EVIDENCE) await fs.writeFile(process.env.VAS_LANGUAGE_EVIDENCE, JSON.stringify(evidence, null, 2));
  console.log('VAS language integration PASS ' + JSON.stringify(evidence));
}
module.exports = { run };
